### ISSUE TITLE
Extra options and comments should be stripped

### ISSUE THREAD

**Issue by wwuck** [Arkq/flake8-requirements#16]
flake8-requirements is using `pkg_resources.parse_requirements` to parse the requirements list.  Looking at the [documentation for parse_requirements](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#requirements-parsing), it only accepts requirement specifiers defined in [PEP508](https://www.python.org/dev/peps/pep-0508/) format.

Full comment lines and line continuation characters are currently handled, but other things still need to be stripped before the requirements lines are passed into `parse_requirements`.  The [requirements file format](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format) allows things like extra options and comments at the end of lines which cause `parse_requirements` to throw an exception.

E.g.

Running this code:
```python3
from pkg_resources import parse_requirements

requirements = parse_requirements('scipy==1.4.1 --hash=sha256:00af72998a46c25bdb5824d2b729e7dabec0c765f9deb0b504f928591f5ff9d4')
for req in requirements:
    print(req)
```
results in the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 13), (line:1, col:14)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3042, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'--hash=s'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    for req in requirements:
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3035, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3044, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'--hash=s'"
```

**Comment by wwuck** [comment]
After another quick test, it looks like comments at the end of a line are handled properly inside `parse_requirements` despite comments not appearing anywhere in the PEP508 spec.
