### ISSUE TITLE
Crash on installs from GitHub

### ISSUE THREAD

**Issue by jamesbraza** [arkq/flake8-requirements#81]
It's possible to `pip install` directly from GitHub like so:

```txt
# requirements.txt
git+https://github.com/AltSchool/dynamic-rest.git@v2.1.7
```

However, `flake8-requirements==2.0.1` with Python 3.10.13 is crashing on this:

```none
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pkg_resources._vendor.pyparsing.exceptions.ParseException: Expected string_end, found '+'  (at char 3), (line:1, col:4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8/checker.py", line 83, in _mp_run
    ).run_checks()
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8/checker.py", line 526, in run_checks
    self.run_ast_checks()
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8/checker.py", line 428, in run_ast_checks
    for line_number, offset, text, _ in runner:
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8_requirements/checker.py", line 754, in run
    for err in filter(None, map(lambda c: c(node), checkers)):
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8_requirements/checker.py", line 754, in <lambda>
    for err in filter(None, map(lambda c: c(node), checkers)):
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8_requirements/checker.py", line 724, in check_I900
    if node.module in self.get_mods_3rd_party(is_setup_py):
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8_requirements/checker.py", line 43, in w
    memoize.mem[k] = f(*args, **kw)
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8_requirements/checker.py", line 687, in get_mods_3rd_party
    for requirement in cls.get_mods_3rd_party_requirements(is_setup_py):
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8_requirements/checker.py", line 705, in get_mods_3rd_party_requirements
    return cls.get_requirements_txt()
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8_requirements/checker.py", line 601, in get_requirements_txt
    return tuple(parse_requirements(cls.resolve_requirement(
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3102, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'+https:/'": Expected string_end
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.10.13/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8/main/application.py", line 187, in _run
    self.run_checks()
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8/main/application.py", line 103, in run_checks
    self.file_checker_manager.run()
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8/checker.py", line 236, in run
    self.run_parallel()
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/flake8/checker.py", line 205, in run_parallel
    self.results = list(pool.imap_unordered(_mp_run, self.filenames))
  File "/Users/user/.pyenv/versions/3.10.13/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'+https:/'": Expected string_end
```

**Comment by jamesbraza** [comment]
https://github.com/pypa/setuptools/issues/2568#issuecomment-821040991 is a valid workaround for this:

```txt
# requirements.txt
dynamic-rest @ git+https://github.com/AltSchool/dynamic-rest.git@v2.1.7
```

Closing this as an upstream issue
